# Generated by Django 4.1 on 2022-12-26 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="groupmember", unique_together=set(),),
        migrations.AlterField(
            model_name="groupmember",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="groups.group",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupmember", unique_together={("group", "user")},
        ),
    ]
